export type Locale = 'pt' | 'en';
export const LOCALES: Locale[] = ['pt', 'en'];
export const DEFAULT_LOCALE: Locale = 'pt';

export const AUTHOR = {
	name: 'André Silva',
	handle: 'ThePerformanceAgent',
	github: 'https://github.com/ThePerformanceAgent',
	repo: 'https://github.com/ThePerformanceAgent/ai-ops-sec',
	linkedin: '', // preencher com o URL público real antes do lançamento
};

export const SITE = {
	pt: {
		title: 'AI Ops Sec',
		tagline: 'Segurança de agentes de IA e observabilidade, com prova.',
		description:
			'Red teaming de agentes, MCP, n8n e OpenTelemetry GenAI, testados num stack real. Cada artigo diz de onde vem cada afirmação.',
		locale: 'pt-PT',
	},
	en: {
		title: 'AI Ops Sec',
		tagline: 'AI agent security and observability, with evidence.',
		description:
			'Red teaming of agents, MCP, n8n and OpenTelemetry GenAI, tested on a real stack. Every article shows where each claim comes from.',
		locale: 'en',
	},
} as const;

export const UI = {
	pt: {
		nav_blog: 'Artigos',
		nav_about: 'Sobre',
		nav_tags: 'Temas',
		skip: 'Saltar para o conteúdo',
		latest: 'Últimos artigos',
		all_posts: 'Todos os artigos',
		read: 'ler',
		min_read: 'min de leitura',
		published: 'publicado',
		updated: 'actualizado',
		verified: 'verificado',
		verified_on: 'verificado a',
		sources: 'fontes',
		sources_title: 'Fontes',
		verified_title: 'O que foi verificado à mão',
		changelog_title: 'Histórico de alterações',
		accessed: 'consultado a',
		lang_switch: 'Read in English',
		lang_switch_short: 'EN',
		theme: 'Alternar tema',
		search: 'Pesquisar',
		trace: 'trace',
		no_posts: 'O primeiro artigo está em revisão. Subscreve o RSS para o receber.',
		rss: 'RSS',
		tags_title: 'Temas',
		tagged: 'Artigos com o tema',
		in_series: 'Série',
		cite: 'Citar este artigo',
		how_built: 'Como este site é construído',
		how_built_items: [
			'Código e artigos num repositório público. Cada alteração entra por pull request revisto.',
			'Sem trackers, sem cookies, sem scripts de terceiros. HTML estático servido por CDN.',
			'Cada artigo lista as fontes, o que foi verificado à mão e o que mudou depois de publicado.',
			'Erros corrigem-se em público, no histórico do próprio artigo.',
		],
		not_found: 'Página não encontrada',
		not_found_body: 'Este endereço não existe ou mudou. O índice de artigos está a um clique.',
		back_home: 'Voltar ao início',
		footer_source: 'Código-fonte',
		footer_license: 'Texto CC BY 4.0 · Código MIT',
		footer_security: 'Reportar falha de segurança',
		footer_no_trackers: 'Sem trackers. Sem cookies.',
		og_kicker: 'AI Ops Sec · segurança de agentes e observabilidade',
	},
	en: {
		nav_blog: 'Articles',
		nav_about: 'About',
		nav_tags: 'Topics',
		skip: 'Skip to content',
		latest: 'Latest articles',
		all_posts: 'All articles',
		read: 'read',
		min_read: 'min read',
		published: 'published',
		updated: 'updated',
		verified: 'verified',
		verified_on: 'verified on',
		sources: 'sources',
		sources_title: 'Sources',
		verified_title: 'What was verified by hand',
		changelog_title: 'Change history',
		accessed: 'accessed',
		lang_switch: 'Ler em português',
		lang_switch_short: 'PT',
		theme: 'Toggle theme',
		search: 'Search',
		trace: 'trace',
		no_posts: 'The first article is under review. Subscribe to the RSS feed to get it.',
		rss: 'RSS',
		tags_title: 'Topics',
		tagged: 'Articles tagged',
		in_series: 'Series',
		cite: 'Cite this article',
		how_built: 'How this site is built',
		how_built_items: [
			'Code and articles live in a public repository. Every change lands through a reviewed pull request.',
			'No trackers, no cookies, no third-party scripts. Static HTML served from a CDN.',
			'Every article lists its sources, what was verified by hand, and what changed after publication.',
			'Mistakes are fixed in public, in the history of the article itself.',
		],
		not_found: 'Page not found',
		not_found_body: 'This address does not exist or has moved. The article index is one click away.',
		back_home: 'Back to home',
		footer_source: 'Source code',
		footer_license: 'Text CC BY 4.0 · Code MIT',
		footer_security: 'Report a security issue',
		footer_no_trackers: 'No trackers. No cookies.',
		og_kicker: 'AI Ops Sec · agent security and observability',
	},
} as const;
